// Generated by gencpp from file ria_teleop/AddTwoInts.msg
// DO NOT EDIT!


#ifndef RIA_TELEOP_MESSAGE_ADDTWOINTS_H
#define RIA_TELEOP_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <ria_teleop/AddTwoIntsRequest.h>
#include <ria_teleop/AddTwoIntsResponse.h>


namespace ria_teleop
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace ria_teleop


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ria_teleop::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::ria_teleop::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::ria_teleop::AddTwoInts > {
  static const char* value()
  {
    return "ria_teleop/AddTwoInts";
  }

  static const char* value(const ::ria_teleop::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::ria_teleop::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::ria_teleop::AddTwoInts > 
template<>
struct MD5Sum< ::ria_teleop::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ria_teleop::AddTwoInts >::value();
  }
  static const char* value(const ::ria_teleop::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ria_teleop::AddTwoIntsRequest> should match 
// service_traits::DataType< ::ria_teleop::AddTwoInts > 
template<>
struct DataType< ::ria_teleop::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::ria_teleop::AddTwoInts >::value();
  }
  static const char* value(const ::ria_teleop::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ria_teleop::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::ria_teleop::AddTwoInts > 
template<>
struct MD5Sum< ::ria_teleop::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ria_teleop::AddTwoInts >::value();
  }
  static const char* value(const ::ria_teleop::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ria_teleop::AddTwoIntsResponse> should match 
// service_traits::DataType< ::ria_teleop::AddTwoInts > 
template<>
struct DataType< ::ria_teleop::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::ria_teleop::AddTwoInts >::value();
  }
  static const char* value(const ::ria_teleop::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RIA_TELEOP_MESSAGE_ADDTWOINTS_H
