<?xml version="1.0"?>

<robot name="RIA-R100">
   
   <include filename="$(find ria_description)/urdf/materials.urdf.xacro" />
   <include filename="$(find ria_description)/urdf/property.urdf.xacro"/>
   <include filename="$(find ria_description)/urdf/wheel.urdf.xacro"/>
   <include filename="$(find ria_description)/urdf/orbbec_astra.urdf.xacro"/>
   <include filename="$(find ria_description)/urdf/sick_tim571.urdf.xacro"/>
<!--
   <link name="odom" >
	<visual>
	   <geometry>
              <cylinder radius="0.03" length="0.01"/>
	   </geometry>
           <origin rpy="0 0 0" xyz="0 0 0"/>
	</visual>   
   </link>

  --> 
   <link name="base_footprint" >
	<visual>
	   <geometry>
              <cylinder radius="0.03" length="0.01"/>
	   </geometry>
           <origin rpy="0 0 0" xyz="0 0 0"/>
	</visual>   
   </link>

   <link name="base_link" >
	<visual>
	   <geometry>
	      <box size="0.03 0.03 0.03" />
	   </geometry>
           <material name="Green"/>
           <origin rpy="0 0 0" xyz="0 0 0"/>
	</visual>   
   </link>

   <link name="RIA_BASE_LOW" >
	<visual>
	   <geometry>
	      <mesh filename="package://ria_description/meshes/lower_body.stl" scale="0.001 0.001 0.001" />
	   </geometry>
           <material name="Dark_Grey"/>
           <origin rpy="${M_PI/2} 0 ${M_PI}" xyz="-0.03 -0.7 0"/>
	</visual>
	<collision>
	   <geometry>
	      <mesh filename="package://ria_description/meshes/lower_body.stl" scale="0.001 0.001 0.001" />
	   </geometry>
	</collision>      
   </link>

   <link name="RIA_BASE_TOP">
      <visual>
         <geometry>
            <mesh filename="package://ria_description/meshes/upper_body.stl" scale="0.001 0.001 0.001"/>
         </geometry>
         <material name="Army_Green"/>
         <origin rpy="${M_PI/2} 0 ${M_PI}" xyz="-0.03 -0.7 0"/>
      </visual>
      <collision>
         <geometry>
            <mesh filename="package://ria_description/meshes/upper_body.stl" scale="0.001 0.001 0.001"/>
         </geometry>
      </collision>
   </link>

<!--
   <joint name="odom_to_base_footprint" type="fixed">
      <parent link="odom"/>
      <child link="base_footprint"/>
      	<origin rpy="0 0 0" xyz="0 0 0"/>
   </joint>
-->

   <joint name="base_footprint_to_base_link" type="fixed">
      <parent link="base_footprint"/>
      <child link="base_link"/>
      	<origin rpy="0 0 0" xyz="0 0 ${BASE_LINK_HEIGHT}"/>
   </joint>
-->
   <joint name="base_link_to_RIA_BASE_LOW" type="fixed">
      <parent link="base_link"/>
      <child link="RIA_BASE_LOW"/>
         <origin rpy="0 0 0" xyz="0 0 0"/>
   </joint>

   <joint name="RIA_BASE_LOW_to_RIA_BASE_TOP" type="fixed">
      <parent link="RIA_BASE_LOW"/>
      <child link="RIA_BASE_TOP"/>
         <origin rpy="0 0 0" xyz="0 0 0"/>
   </joint>

   <joint name="base_link_to_wheel_fl" type="fixed">
      <parent link="base_link"/>
      <child link="WHEEL_FL"/>
         <origin rpy="0 0 0" xyz="${WHEEL_X} ${WHEEL_Y} ${WHEEL_SIZE/2 - BASE_LINK_HEIGHT}"/>
   </joint>

   <joint name="base_link_to_wheel_fr" type="fixed">
      <parent link="base_link"/>
      <child link="WHEEL_FR"/>
         <origin rpy="0 0 0" xyz="${WHEEL_X} ${-WHEEL_Y} ${WHEEL_SIZE/2 - BASE_LINK_HEIGHT}"/>
   </joint>

   <joint name="base_link_to_wheel_bl" type="fixed">
      <parent link="base_link"/>
      <child link="WHEEL_BL"/>
         <origin rpy="0 0 0" xyz="${-WHEEL_X} ${WHEEL_Y} ${WHEEL_SIZE/2 - BASE_LINK_HEIGHT}"/>
   </joint>

   <joint name="base_link_to_wheel_br" type="fixed">
      <parent link="base_link"/>
      <child link="WHEEL_BR"/>
         <origin rpy="0 0 0" xyz="${-WHEEL_X} ${-WHEEL_Y} ${WHEEL_SIZE/2 - BASE_LINK_HEIGHT}"/>
   </joint>
</robot>




